-- Ensure clienttype_id auto-generates
ALTER TABLE clienttype
  ALTER COLUMN clienttype_id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Add client types: Corporation, Inc., and Cooperative
INSERT INTO clienttype (business_type) VALUES 
  ('Corporation'),
  ('Inc.'),
  ('Cooperative')
ON CONFLICT DO NOTHING;

-- View all client types
SELECT * FROM clienttype ORDER BY clienttype_id;
